# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'armEjemplo'
    subscriptionId: '9486076a-8d2f-43bc-94ba-3a6001a252f4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'felixitogroup'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/felixnoga/azureRmPipeline/main/webapp/azuredeploy.json'
    overrideParameters: '-projectName azurearm'
    deploymentMode: 'Incremental'
